### PR TITLE
Introduce click to open trigger

### PR DESCRIPTION
**Pull request by jedrula**
I'd like to propose a PR from a fork I am using in a production application.
The idea here is that instead of one `click` trigger there is two: `clickToOpen` and `clickToToggle`. The `clickToToggle` behaves same as `click` used to (we could keep `click` trigger for backwards compatibility) while `clickToOpen` makes sure that once popper is opened any subsequent clicks on the popper won't close it but rather keep it opened. So when you use the `clickToOpen` trigger you close the popper only by clicking **outside** of the popper element.

If you think this feature is something that others can benefit from I can provide some documentation for the new trigger and make the PR backwards compatible. 

In case there is other ways of achieve what my fork does using the original code that is in master branch It would be great to get some advice and then we could simply close this PR.

Thanks for a great vue lib!

### CODE REVIEW

**Comment by RobinCK** [comment]
Thanks, good idea, it would be nice to keep click for backward compatibility.
Also, update documentation

**Comment by jedrula** [comment]
@RobinCK - updated documentation and provided backwards functionality

**Comment by RobinCK** [comment]
thanks, but table broke in readme file
jedrulavue-popper+at+introduce-click-to-open-trigger+2019-10-04+07-40-26

**Comment by jedrula** [comment]
Oops - my bad with the table - one empty row sneaked in and that broke it. Should be ok now.

**Comment by RobinCK** [comment]
thanks

**Pull request merged**
